export const GET_CHARACTERS = 'GET_CHARACTERS';
export const ERROR_CHARACTERS = 'ERROR_CHARACTERS';

export const GET_COMICS = 'GET_COMICS';
export const ERROR_COMICS = 'ERROR_COMICS';

export const SET_LOADING = 'SET_LOADING';
